apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyter-notebook
  labels:
    app: jupyter-notebook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyter-notebook
  template:
    metadata:
      labels:
        app: jupyter-notebook
    spec:
      containers:
      - name: jupyter-notebook
        image: mlrun/jupy:latest
        env:
        - name: MLRUN_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: JUPYTER_ENABLE_LAB
          value: "yes"
        - name: MLRUN_DBPATH
          value: "http://mlrun-api:8080"
        - name: MLRUN_ARTIFACT_PATH
          value: "/home/jovyan/data"
        volumeMounts:
        - mountPath: /home/jovyan/data
          name: pvclocal
        ports:
        - containerPort: 8888
          name: jupy
        - containerPort: 8080
          name: mlrun-api
        command: ["start-notebook.sh"]
        args:
        - --ip="0.0.0.0"
        - --port=8888
        - --NotebookApp.token=''
        - --NotebookApp.password=''
        - --NotebookApp.default_url="/lab"
      volumes:
        - name: pvclocal
          persistentVolumeClaim:
            claimName: pvclocal    
      serviceAccountName: mlrun-api

---

kind: Service
apiVersion: v1
metadata:
  name: jupyter-notebook
spec:
  type: NodePort
  selector:
    app: jupyter-notebook
  ports:
  - protocol: TCP
    nodePort: 30040
    port: 8888
    targetPort: 8888


---

kind: Service
apiVersion: v1
metadata:
  name: mlrun-api
spec:
  type: NodePort
  selector:
    app: jupyter-notebook
  ports:
  - protocol: TCP
    nodePort: 30080
    port: 8080
    targetPort: 8080

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mlrun-api
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mlrun-api-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - pods/exec
  - pods/log
  - services
  verbs:
  - '*'
- apiGroups:
  - kubeflow.org
  resources:
  - mpijobs
  verbs:
  - '*'
- apiGroups:
  - sparkoperator.k8s.io
  resources:
  - sparkapplications
  - scheduledsparkapplications
  verbs:
  - '*'

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mlrun-api-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: mlrun-api-role
subjects:
- kind: ServiceAccount
  name: mlrun-api
