apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvlocal
spec:
  capacity:
    storage: 100Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /tmp/mlrun
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - master
          - host01
          - host02

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvclocal
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: local-storage
  resources:
    requests:
      storage: 100Gi
